### ISSUE TITLE
How can I expose the containers to Nginx? 

### ISSUE THREAD

**Issue by Sshuichi** [rudderlabs/rudderstack-helm#12]
I'm trying to have the server on track.domain.com 
I don't know which port is being exposed so I can use it in proxy_pass. 
Could you please help me here? 
Thank you.

**Comment by harshmanvar** [comment]
@Sshuichi  i have deployed GKE but getting 404 when opening loadbalancer IP. i have used the example : https://github.com/rudderlabs/rudderstack-helm/blob/master/workspaceConfig.json.example for WorkSpaceConfig.json .

if you can please help is it related to Nginx but since i have used LB as service so no Nginx between but my UI or console is not coming up?
