### ISSUE TITLE
Use existing running postgress instance in GKE ?

### ISSUE THREAD

**Issue by harshmanvar** [rudderlabs/rudderstack-helm#16]
Is it possible to use existing Postgres instance with rudder stack ? 

Please let me know how to configure values. as i am not seeing anything specific related to it in readme so.

**Comment by snarkychef** [comment]
One of the users from community @pandres95 has figured this out. Refer
https://discordapp.com/channels/625629179697692673/625629179697692677/740965601371095051 

Excerpt from above message,

```
Clone chart repo.
- Remove postgresql subchart.
- Remove pg config files on root.
- On statefulset.yaml:
    - Remove COMPUTE_DB_HOST_IN_K8S, POSTGRES_POD_NAME,  and POSTGRESS_HEADLESS_SVC variables.
    - Set JOBS_DB_HOST, JOBS_DB_USER, JOBS_DB_PASSWORD values according to my connection.
```

Please take care of below things, which are currently taken care by the postgresql chart :
- JOBS_DB_USER will need `CREATE DB` privilege 
- JOBS_DB_DB_NAME need to created externally (use JOBS_DB_USER creds to create one)
- JOBS_DB_USER should be owner of JOBS_DB_DB_NAME


Any contributions in the repo to implement this more seamlessly is highly appreciated. Otherwise, we will take this up when time permits.

**Comment by snarkychef** [comment]
Closing the issue due to inactivity.
